/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KaristirilanlarRouteImport } from './routes/karistirilanlar'
import { Route as KatalogRouteImport } from './routes/katalog'
import { Route as LaboratuvarRouteImport } from './routes/laboratuvar'
import { Route as PcRouteImport } from './routes/pc'
import { Route as SohbetRouteImport } from './routes/sohbet'
import { Route as TestRouteImport } from './routes/test'
import { Route as YapimciRouteImport } from './routes/yapimci'
import { Route as YolRouteImport } from './routes/yol'
import { Route as AtlasIndexRouteImport } from './routes/atlas.index'
import { Route as AtlasSlugRouteImport } from './routes/atlas.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KaristirilanlarRoute = KaristirilanlarRouteImport.update({
  id: '/karistirilanlar',
  path: '/karistirilanlar',
  getParentRoute: () => rootRouteImport,
} as any)
const KatalogRoute = KatalogRouteImport.update({
  id: '/katalog',
  path: '/katalog',
  getParentRoute: () => rootRouteImport,
} as any)
const LaboratuvarRoute = LaboratuvarRouteImport.update({
  id: '/laboratuvar',
  path: '/laboratuvar',
  getParentRoute: () => rootRouteImport,
} as any)
const PcRoute = PcRouteImport.update({
  id: '/pc',
  path: '/pc',
  getParentRoute: () => rootRouteImport,
} as any)
const SohbetRoute = SohbetRouteImport.update({
  id: '/sohbet',
  path: '/sohbet',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const YapimciRoute = YapimciRouteImport.update({
  id: '/yapimci',
  path: '/yapimci',
  getParentRoute: () => rootRouteImport,
} as any)
const YolRoute = YolRouteImport.update({
  id: '/yol',
  path: '/yol',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasIndexRoute = AtlasIndexRouteImport.update({
  id: '/atlas/',
  path: '/atlas/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasSlugRoute = AtlasSlugRouteImport.update({
  id: '/atlas/$slug',
  path: '/atlas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/karistirilanlar': typeof KaristirilanlarRoute
  '/katalog': typeof KatalogRoute
  '/laboratuvar': typeof LaboratuvarRoute
  '/pc': typeof PcRoute
  '/sohbet': typeof SohbetRoute
  '/test': typeof TestRoute
  '/yapimci': typeof YapimciRoute
  '/yol': typeof YolRoute
  '/atlas/$slug': typeof AtlasSlugRoute
  '/atlas/': typeof AtlasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/karistirilanlar': typeof KaristirilanlarRoute
  '/katalog': typeof KatalogRoute
  '/laboratuvar': typeof LaboratuvarRoute
  '/pc': typeof PcRoute
  '/sohbet': typeof SohbetRoute
  '/test': typeof TestRoute
  '/yapimci': typeof YapimciRoute
  '/yol': typeof YolRoute
  '/atlas/$slug': typeof AtlasSlugRoute
  '/atlas': typeof AtlasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/karistirilanlar': typeof KaristirilanlarRoute
  '/katalog': typeof KatalogRoute
  '/laboratuvar': typeof LaboratuvarRoute
  '/pc': typeof PcRoute
  '/sohbet': typeof SohbetRoute
  '/test': typeof TestRoute
  '/yapimci': typeof YapimciRoute
  '/yol': typeof YolRoute
  '/atlas/$slug': typeof AtlasSlugRoute
  '/atlas/': typeof AtlasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/karistirilanlar'
    | '/katalog'
    | '/laboratuvar'
    | '/pc'
    | '/sohbet'
    | '/test'
    | '/yapimci'
    | '/yol'
    | '/atlas/$slug'
    | '/atlas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/karistirilanlar'
    | '/katalog'
    | '/laboratuvar'
    | '/pc'
    | '/sohbet'
    | '/test'
    | '/yapimci'
    | '/yol'
    | '/atlas/$slug'
    | '/atlas'
  id:
    | '__root__'
    | '/'
    | '/karistirilanlar'
    | '/katalog'
    | '/laboratuvar'
    | '/pc'
    | '/sohbet'
    | '/test'
    | '/yapimci'
    | '/yol'
    | '/atlas/$slug'
    | '/atlas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KaristirilanlarRoute: typeof KaristirilanlarRoute
  KatalogRoute: typeof KatalogRoute
  LaboratuvarRoute: typeof LaboratuvarRoute
  PcRoute: typeof PcRoute
  SohbetRoute: typeof SohbetRoute
  TestRoute: typeof TestRoute
  YapimciRoute: typeof YapimciRoute
  YolRoute: typeof YolRoute
  AtlasSlugRoute: typeof AtlasSlugRoute
  AtlasIndexRoute: typeof AtlasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karistirilanlar': {
      id: '/karistirilanlar'
      path: '/karistirilanlar'
      fullPath: '/karistirilanlar'
      preLoaderRoute: typeof KaristirilanlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katalog': {
      id: '/katalog'
      path: '/katalog'
      fullPath: '/katalog'
      preLoaderRoute: typeof KatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laboratuvar': {
      id: '/laboratuvar'
      path: '/laboratuvar'
      fullPath: '/laboratuvar'
      preLoaderRoute: typeof LaboratuvarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pc': {
      id: '/pc'
      path: '/pc'
      fullPath: '/pc'
      preLoaderRoute: typeof PcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sohbet': {
      id: '/sohbet'
      path: '/sohbet'
      fullPath: '/sohbet'
      preLoaderRoute: typeof SohbetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yapimci': {
      id: '/yapimci'
      path: '/yapimci'
      fullPath: '/yapimci'
      preLoaderRoute: typeof YapimciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yol': {
      id: '/yol'
      path: '/yol'
      fullPath: '/yol'
      preLoaderRoute: typeof YolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas/': {
      id: '/atlas/'
      path: '/atlas'
      fullPath: '/atlas/'
      preLoaderRoute: typeof AtlasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas/$slug': {
      id: '/atlas/$slug'
      path: '/atlas/$slug'
      fullPath: '/atlas/$slug'
      preLoaderRoute: typeof AtlasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KaristirilanlarRoute: KaristirilanlarRoute,
  KatalogRoute: KatalogRoute,
  LaboratuvarRoute: LaboratuvarRoute,
  PcRoute: PcRoute,
  SohbetRoute: SohbetRoute,
  TestRoute: TestRoute,
  YapimciRoute: YapimciRoute,
  YolRoute: YolRoute,
  AtlasSlugRoute: AtlasSlugRoute,
  AtlasIndexRoute: AtlasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
